import { ALL_STATUS } from '../../../constants/investmentStatus';

export const mock = [
  {
    id: 1,
    createdAt: '2/3/2022',
    amount: 199,
    token_from: 'usdc',
    token_to: 'chainlink',
    status: ALL_STATUS.ACTIVE,
    progress: 32,
  },
  {
    id: 2,
    createdAt: '8/30/2021',
    amount: 883,
    token_from: 'usdc',
    token_to: 'btc',
    status: ALL_STATUS.PAUSED,
    progress: 14,
  },
  {
    id: 3,
    createdAt: '2/25/2022',
    amount: 48,
    token_from: 'usdt',
    token_to: 'btc',
    status: ALL_STATUS.ACTIVE,
    progress: 33,
  },
  {
    id: 4,
    createdAt: '5/29/2022',
    amount: 54,
    token_from: 'usdc',
    token_to: 'sol',
    status: ALL_STATUS.COMPLETE,
    progress: 100,
  },
  {
    id: 5,
    createdAt: '3/8/2022',
    amount: 133,
    token_from: 'usdc',
    token_to: 'sol',
    status: ALL_STATUS.ACTIVE,
    progress: 41,
  },
  {
    id: 6,
    createdAt: '3/7/2022',
    amount: 782,
    token_from: 'usdt',
    token_to: 'ftt',
    status: ALL_STATUS.ACTIVE,
    progress: 6,
  },
  {
    id: 7,
    createdAt: '2/24/2022',
    amount: 870,
    token_from: 'usdc',
    token_to: 'btc',
    status: ALL_STATUS.PAUSED,
    progress: 92,
  },
  {
    id: 8,
    createdAt: '1/1/2022',
    amount: 854,
    token_from: 'usdt',
    token_to: 'chainlink',
    status: ALL_STATUS.ACTIVE,
    progress: 46,
  },
  {
    id: 9,
    createdAt: '2/7/2022',
    amount: 617,
    token_from: 'usdt',
    token_to: 'sol',
    status: ALL_STATUS.ACTIVE,
    progress: 20,
  },
  {
    id: 10,
    createdAt: '10/14/2021',
    amount: 377,
    token_from: 'usdt',
    token_to: 'chainlink',
    status: ALL_STATUS.PAUSED,
    progress: 10,
  },
];
